### ISSUE TITLE
Need to cherry-pick commits into Development after Capri release into Master

### ISSUE THREAD

**Issue by xing-yang** [sodafoundation/dashboard#166]
There are some PRs that got merged into Development branch after the Capri release.
They need to be cherry-picked into Master, otherwise they will be lost because Development branch is deprecated.

@anvithks Can you check and make sure all commits merged into Development after Capri release are cherry-picked into Master?

**Comment by anvithks** [comment]
Sure @xing-yang.
I think there are a few more PR's that may be raised to fix some of the issues raised here. 
Do we wait for those or cherry pick now and again later?

**Comment by leonwanghui** [comment]
@xing-yang @anvithks Fixed by #169

**Comment by leonwanghui** [comment]
Please notice #60 is abandoned for 13 commits merged which is difficult to be cherry-picked, @Click2Cloud-Gamma can u repull the patch to the master branch? Thanks!

**Comment by leonwanghui** [comment]
#60 Will be repulled by @jimccfun and @yuejuSDS

**Comment by anvithks** [comment]
@jimccfun Was this completed or is it still to be done?

**Comment by anvithks** [comment]
@Click2Cloud-Gamma Please check this. It was difficult to merge the commits from #60 to master. Could you please check if your changes were merged to master branch.  
If not, then please raise a PR to the master branch so that we can get them aligned. @leonwanghui faced some issues with cherry-picking.

**Comment by Click2Cloud-Gamma** [comment]
@anvithks I will raise a PR for the same ASAP. Thanks.

**Comment by anvithks** [comment]
> @anvithks I will raise a PR for the same ASAP. Thanks.

@Click2Cloud-Gamma Thank you. Please do check if the changes are already in master. Since there was some cherry-picking done already.

**Comment by Click2Cloud-Gamma** [comment]
@anvithks Please review #191 . Thanks

**Comment by anvithks** [comment]
Closing this as this seems to be a stale issue and the branch has been updated.
