### ISSUE TITLE
profile: The console has more than one query profiles request and query of the pools, it is not reasonable

### ISSUE THREAD

**Issue by jimccfun** [sodafoundation/dashboard#182]
**Is this a BUG REPORT or FEATURE REQUEST?:**

Uncomment only one, leave it on its own line:

/kind bug
/kind feature

**What happened:**
1.Click "profile" in the left tree menu bar, enter the profile page
2.The console has more than one query profiles request and query of the pools, it is not reasonable
![3Z%ORNBL7CSCNQE@{2KEVB3](https://user-images.githubusercontent.com/37950702/61780921-0103bd00-ae36-11e9-9a03-cee76fec44ad.png)

**What you expected to happen:**
When entering the profile page, only need a query profiles of the request, and a query request of pools
**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know?:**

**Environment:**

Hotpot(release/branch) version:
OS (e.g. from /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Others:

**Comment by anvithks** [comment]
Closing. Already fixed.
