### ISSUE TITLE
No description in volume update page

### ISSUE THREAD

**Issue by wisererik** [sodafoundation/dashboard#239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
 /kind bug

**What happened**:
No description in volume update page

![Selection_046](https://user-images.githubusercontent.com/9572954/70447022-0e0f0900-1ac4-11ea-84a3-6ca89fe5db5f.png)

**What you expected to happen**:

description should be in volume update page

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- dashboard(release/branch) version: latest image
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: *latest hotpot with swagger validation*

**Comment by anvithks** [comment]
@wisererik Volume create does not have a description field. So modify cannot be provided.

**Comment by anvithks** [comment]
After checking and verifying the response of the Volume there is no description field. 
Closing.
![vol-desc-2](https://user-images.githubusercontent.com/19162717/84978722-4bc3ad00-b14b-11ea-8938-d69aeaa6990f.png)
![vol-desc-1](https://user-images.githubusercontent.com/19162717/84978733-4d8d7080-b14b-11ea-9297-4374f9f69c66.png)
