### ISSUE TITLE
After clicking create volume instance always throws this 400 error on web page

### ISSUE THREAD

**Issue by Shruthi-1MN** [sodafoundation/dashboard#252]
In Services menu, after clicking on volume create it throws the below error please find the screen shot
![Screenshot from 2019-12-18 15-59-20](https://user-images.githubusercontent.com/48908765/71078968-5dce8e00-21b0-11ea-9563-c465d11c542f.png)

**Comment by anvithks** [comment]
@Shruthi-1MN please attach the network call request and response from the developer console (F12 -> Network tab)

**Comment by anvithks** [comment]
I was not able to recreate this issue. Also it seems like an environment setup issue. Closing.
