### ISSUE TITLE
[QIP][DAITO] Create Bucket in Huawei cloud fails with 500 error but succeeds in Backend

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#291]
Steps:
Create Bucket with Huawei_obs as backend
Create fails with error 500 internal server.
Message is displayed in UI too.
But from backend DB the bucket is created.
Once page is refreshed, bucket appears in UI too
![image](https://user-images.githubusercontent.com/48085413/73454064-51367b80-4393-11ea-80ec-a423e99014c0.png)
From browser:
Request URL: http://192.168.20.163:8088/v1/s3/aksbkt1
Request Method: PUT
Status Code: 500 Internal Server Error
Remote Address: 192.168.20.163:8088
Referrer Policy: no-referrer-when-downgrade

mysql> select * from buckets;
+------------+----------------------------------+----------------------------------+---------------------+--------+----------+---------+------+--------------------------+------+------+--------+------------+-------------+---------------------+
| bucketname | tenantid                         | userid                           | createtime          | usages | location | deleted | tier | acl                      | cors | lc   | policy | versioning | replication | update_time         |
+------------+----------------------------------+----------------------------------+---------------------+--------+----------+---------+------+--------------------------+------+------+--------+------------+-------------+---------------------+
| aksbkt2    | 94b280022d0c4401bcf3b0ea85870519 | 558057c4256545bd8a307c37464003c9 | 2020-01-30 18:40:36 |      0 | aws_bknd |       0 |    1 | {"cannedAcl": "private"} | null | null | ""     | Disabled   | null        | 2020-01-30 13:10:36 |
| aksbkt1    | 94b280022d0c4401bcf3b0ea85870519 | 558057c4256545bd8a307c37464003c9 | 2020-01-30 19:00:44 |      0 | hws_bknd |       0 |    1 | {"cannedAcl": "private"} | null | null | ""     | Disabled   | null        | 2020-01-30 13:30:44 |
+------------+----------------------------------+----------------------------------+---------------------+--------+----------+---------+------+--------------------------+------+------+--------+------------+-------------+---------------------+
2 rows in set (0.00 sec)
![image](https://user-images.githubusercontent.com/48085413/73454093-614e5b00-4393-11ea-8bda-9960cf4615b9.png)

**Comment by anvithks** [comment]
@kumarashit Do you have the screenshot of the Network tab from the Developer toolbar. The 500 internal server error is a generic one and is thrown mostly when some backend module is down.

**Comment by anvithks** [comment]
Closing since could not reproduce this. Please reopen if this issue persists

**Comment by kumarashit** [comment]
As you could not reproduce the issue, please attach a screenshot or evidence and then close the issue.

**Comment by anvithks** [comment]
Sure @kumarashit .
Check out these screenshots below.
![create-hws-bucket-1](https://user-images.githubusercontent.com/19162717/81002614-27479600-8e67-11ea-8781-41e6a3333969.png)
![create-hws-bucket-2](https://user-images.githubusercontent.com/19162717/81002619-29115980-8e67-11ea-804d-7fe298d291b3.png)
![create-hws-bucket-3](https://user-images.githubusercontent.com/19162717/81002621-2a428680-8e67-11ea-9110-1e1953ab11f5.png)

**Comment by kumarashit** [comment]
Thanks @anvithks
