### ISSUE TITLE
OpenSDS dashboard sends Download successful message on cancelling the download

### ISSUE THREAD

**Issue by nguptaopensds** [sodafoundation/dashboard#293]
1. Click on Download tab in objects
2. On the browse window which pops up after that, hit cancel
3. The "Download successfully" message comes up.

![image](https://user-images.githubusercontent.com/48784300/73536201-77b7ed80-444b-11ea-89c1-29240b7bf81c.png)

**Comment by anvithks** [comment]
Duplicate of #286

**Comment by anvithks** [comment]
Closing this as duplicate.
