### ISSUE TITLE
Delfin UI - Register Storage

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#378]
**Issue/Feature Description:**
Add 

- [x] Register storage page 

- [x] Accept access info params

- [x] Validate input

- [x] Register storage

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Provide user interface for register storage for discovery and monitoring
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
The register storage page was developed based on Delfin v0.1.0 APIs.
There were changes made to the API as part of the auth process.
Started work on modifying the input params to match the changes to support `rest` and `ssh`
