### ISSUE TITLE
Delfin UI - Storage Summary Dashboard

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#379]
**Issue/Feature Description:**
Create a page for Storage Summary 
Implement the API to list all storage resources

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Show all the required info when user has a registered a storage

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
This page will have a summary of the available storage arrays listed by Vendor / Mdoel.
Clicking on the name will show the details and hovering will show a quick summary of the array capacity and any immediate risk.
This page will also list alerts that have not been closed.
This page will show the total raw capacity usage summary  and  Usable capacity summary across storage arrays.

**Proposed UI** 
![delfin-prototype-storage-summary-1](https://user-images.githubusercontent.com/19162717/91381904-1a9be300-e846-11ea-98b9-404010c78d1c.png)
