### ISSUE TITLE
Cleanup on failed installation not cleaning completely

### ISSUE THREAD

**Issue by reshmi-tr** [sodafoundation/dashboard#447]
**Environment details:**
SODA version:  SODA v1.1.0 Greenland
OS: Ubuntu 18.04,Oracle VM Virtual Box
Storage details : Controller: IDE(VBoxGuestAdditions.iso) : 57.82MB
                          Controller:SATA(Ubuntu 18.04) : virtual size: 80GB, dynamically allocated

**Steps used:**
1.Followed installation of Greenland on Ubuntu 18.04,virtual box, using release notes and using ANSIBLE
2.No error observed till - Run SODA installer ansible playbook to start deploy
3.Got the below error in first run:
TASK [auth-installer : install keystone with the docker] ***********************

failed: [localhost] (item=bash ./script/keystone.sh install docker) => {"changed": true, "cmd": "bash ./script/keystone.sh install docker", "delta": "0:07:30.783185", "end": "2020-10-07 15:05:03.342344", "item": "bash ./script/keystone.sh install docker", "msg": "non-zero return code", "rc": 1, "start": "2020-10-07 14:57:32.559159", "stderr": "", "stderr_lines": [], "stdout": "Starting install keystone...\nlatest: Pulling from opensdsio/opensds-authchecker\n34667c7e4631: Pulling fs layer\nd18d76a881a4: Pulling fs layer\n119c7358fbfc: Pulling fs layer\n2aaf13f3eff0: Pulling fs layer\n5824c5a940ae: Pulling fs layer\n7ebdbe4554b7: Pulling fs layer\n5c860faddb96: Pulling fs layer\n57ff77583ca8: Pulling fs layer\n29146555bfc7: Pulling fs layer\n164a9401817c: Pulling fs layer\n7ebdbe4554b7: Waiting\n5c860faddb96: Waiting\n164a9401817c: Waiting\n29146555bfc7: Waiting\n57ff77583ca8: Waiting\n5824c5a940ae: Waiting\n2aaf13f3eff0: Waiting\n119c7358fbfc: Download complete\nd18d76a881a4: Verifying Checksum\nd18d76a881a4: Download complete\n2aaf13f3eff0: Verifying Checksum\n2aaf13f3eff0: Download complete\n5824c5a940ae: Verifying Checksum\n5824c5a940ae: Download complete\n7ebdbe4554b7: Verifying Checksum\n7ebdbe4554b7: Download complete\n57ff77583ca8: Verifying Checksum\n57ff77583ca8: Download complete\n34667c7e4631: Verifying Checksum\n34667c7e4631: Download complete\n5c860faddb96: Verifying Checksum\n5c860faddb96: Download complete\n34667c7e4631: Pull complete\nd18d76a881a4: Pull complete\n119c7358fbfc: Pull complete\n2aaf13f3eff0: Pull complete\n5824c5a940ae: Pull complete\n7ebdbe4554b7: Pull complete\n164a9401817c: Verifying Checksum\n5c860faddb96: Pull complete\n57ff77583ca8: Pull complete\n29146555bfc7: Verifying Checksum\n29146555bfc7: Download complete\n29146555bfc7: Pull complete\n164a9401817c: Pull complete\nDigest: sha256:342f5cd850e65fcd9d5ad0b435e3398f7ce1980bb7a08d3fd0e34ce72972de16\nStatus: Downloaded newer image for opensdsio/opensds-authchecker:latest\n9dfbbcf7989e7cf18bf28c76f02154da1737ac8a7df93a6194b84f0d258bc111\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}\nERROR: keystone didn't come up. Aborting...", "stdout_lines": ["Starting install keystone...", "latest: Pulling from opensdsio/opensds-authchecker", "34667c7e4631: Pulling fs layer", "d18d76a881a4: Pulling fs layer", "119c7358fbfc: Pulling fs layer", "2aaf13f3eff0: Pulling fs layer", "5824c5a940ae: Pulling fs layer", "7ebdbe4554b7: Pulling fs layer", "5c860faddb96: Pulling fs layer", "57ff77583ca8: Pulling fs layer", "29146555bfc7: Pulling fs layer", "164a9401817c: Pulling fs layer", "7ebdbe4554b7: Waiting", "5c860faddb96: Waiting", "164a9401817c: Waiting", "29146555bfc7: Waiting", "57ff77583ca8: Waiting", "5824c5a940ae: Waiting", "2aaf13f3eff0: Waiting", "119c7358fbfc: Download complete", "d18d76a881a4: Verifying Checksum", "d18d76a881a4: Download complete", "2aaf13f3eff0: Verifying Checksum", "2aaf13f3eff0: Download complete", "5824c5a940ae: Verifying Checksum", "5824c5a940ae: Download complete", "7ebdbe4554b7: Verifying Checksum", "7ebdbe4554b7: Download complete", "57ff77583ca8: Verifying Checksum", "57ff77583ca8: Download complete", "34667c7e4631: Verifying Checksum", "34667c7e4631: Download complete", "5c860faddb96: Verifying Checksum", "5c860faddb96: Download complete", "34667c7e4631: Pull complete", "d18d76a881a4: Pull complete", "119c7358fbfc: Pull complete", "2aaf13f3eff0: Pull complete", "5824c5a940ae: Pull complete", "7ebdbe4554b7: Pull complete", "164a9401817c: Verifying Checksum", "5c860faddb96: Pull complete", "57ff77583ca8: Pull complete", "29146555bfc7: Verifying Checksum", "29146555bfc7: Download complete", "29146555bfc7: Pull complete", "164a9401817c: Pull complete", "Digest: sha256:342f5cd850e65fcd9d5ad0b435e3398f7ce1980bb7a08d3fd0e34ce72972de16", "Status: Downloaded newer image for opensdsio/opensds-authchecker:latest", "9dfbbcf7989e7cf18bf28c76f02154da1737ac8a7df93a6194b84f0d258bc111", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: {'auth': {'scope': {'project': {'domain': {'name': 'Default'}, 'name': 'admin'}}, 'identity': {'password': {'user': {'domain': {'name': 'Default'}, 'password': 'opensds@123', 'name': 'admin'}}, 'methods': ['password']}}}", "ERROR: keystone didn't come up. Aborting..."]}
	to retry, use: --limit @/home/rtr/installer/ansible/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=15   unreachable=0    failed=1   

4. Tried to run again and got error as below:
TASK [auth-installer : check port usage] *******************************************************************************************************************************************************************
failed: [localhost] (item=80) => {"changed": false, "elapsed": 5, "item": 80, "msg": "Port 80 is not free"}
	to retry, use: --limit @/home/rtr/installer/ansible/site.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=13   changed=2    unreachable=0    failed=1

**Comment by himanshuvar** [comment]
@reshmi-tr Try the following:

Check for the process.

`ps -aux | grep apache2`

Kill the above process & Run SODA installer ansible playbook to start deployment

**Comment by anvithks** [comment]
@reshmi-tr Please use code blocks for including code (errors or command line output as well.)

I have raised the issue in the correct repository [installer / #339](https://github.com/sodafoundation/installer/issues/399)
Please check there for any updates.

Closing this issue as this is not a dashboard issue.
