### ISSUE TITLE
Hosts should be discovered and not Created in the Resource Manager -> Hosts Page.

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/dashboard#470]
**Issue/Feature Description:**
Hosts should be discovered instead of Created in the Resource Manger Page . 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

![](https://files.slack.com/files-pri/T2YSV6N2J-F01DK4ZU030/image.png)

**Comment by rajat-soda** [comment]
![image (2)](https://user-images.githubusercontent.com/65751939/97861040-2665c300-1d29-11eb-9fa9-ace0cba5ac4c.png)

**Comment by kumarashit** [comment]
What is the idea here? Which host to discover? In a DC i can have multiple hosts which need not be part of discovery, how can this be filtered. Also, how to provide Host discovery details?

**Comment by rajat-soda** [comment]
The terminology used here is not right, we are not creating any host here, we are just discovering a host or at best adding it to SODA. The process of adding / discovering a host is not questioned here.. just the terminology.
