### ISSUE TITLE
[Delfin UI] Setup Prometheus with Delfin and explore integration with Grafana for performance monitoring

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/dashboard#471]
**Issue/Feature Description:**
Follow the installation guide as per the [examples](https://github.com/sodafoundation/examples/tree/master/DelfinPerformance) and install Prometheus and Delfin. Install Grafana and explore integration with this setup for displaying the performance metrics from Delfin.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Delfin supports performance monitoring metrics using the Prometheus exporter. Prometheus works well with Grafana for visualisation and it provides a comprehensive set of charts and graphs to show the metrics intuitively. 

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
- Installed Prometheus and setup the delfin performance metrics collection.
- Installed Grafana and connected it to the Prometheus endpoint. Able to view the metrics in Grafana.
![image](https://user-images.githubusercontent.com/19162717/98159925-684a6100-1f03-11eb-84ee-3353a53727bd.png)

- Started with Grafana basic configuration and learning how to customize the dashboard. 

- Installed [netdata](https://github.com/netdata/netdata#get-netdata) and tried to integrate with the performance collection of delfin. Need to understand how to setup a custom collector to integrate.

**Comment by anvithks** [comment]
Successfully setup SODA with delfin v1.0.0. Setup prometheus using docker and configured it to read from the configuration file specified at the time of starting the docker image.
Installed Grafana using docker and configured it with prometheus. Able to visualize the metrics.
![image](https://user-images.githubusercontent.com/19162717/98705049-4dfd0100-23a3-11eb-8d36-7ca034b563b7.png)

Customized the Grafana Dashboard and added filters to filter by storage id.

![image](https://user-images.githubusercontent.com/19162717/98705077-52c1b500-23a3-11eb-9e10-57ef105392db.png)

Need to do the following:

- [ ] Create a docker-compose.yml file to install Prometheus and Grafana from docker.
- [ ] Configure Prometheus to persist data by setting up a docker volume and map to configuration file from the host.
- [ ] Configure Grafana to persist data by setting up a docker volume and sync with Prometheus. Initiate Grafana with a default dashboard that is preconfigured to show delfin metrics (as shown in screen shot above.)
- [ ] Grafana Authentication: Need to check whether SODA Auth with Keystone can be used for Grafana or any other mechanism supported.
- [ ] Integration of Grafana in SODA Dashboard; Embed or seamless link. Style Grafana as per SODA colors?

@NajmudheenCT @PravinRanjan10 @kumarashit 
I will need help with the following:
- Can we add / remove fields that are received in the Prometheus output? Having a storage array name will make it easier to identify than the id.
`storage_throughput{instance="localhost:8195",job="delfin",resource_type="array",storage_id="01f3134c-541c-4c1a-a7ff-efaf32e0a73f",type="RAW",unit="IOPS",value_type="gauge"}`
- What are the other metrics that we are targeting for Hawaii release and their types? 
- If there are multiple categories of metrics we can have different dashboards with filters. Let us discuss this.

**Comment by kumarashit** [comment]
Backlog of Iter1
