### ISSUE TITLE
[Multicloud UI] Object names are prefixed with null when an object is uploaded on a fresh installation of SODA

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/dashboard#500]
**Issue/Feature Description:**
When an object is uploaded to multicloud backend on a fresh installation of SODA the object name is prefixed with null. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
User is unable to delete the object until another object is first created which uploads with correct name.

**How to reproduce, in case of a bug:**
1. Install SODA
2. On a fresh installation register a cloud backend
2. Create a bucket
3. Upload an object

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
![create-object-null-in-name](https://user-images.githubusercontent.com/19162717/103169573-f1767800-4862-11eb-9db2-952103b6b94a.png)

**Comment by PravinRanjan10** [comment]
This issue was found during folder creation. In RC2 of L release
![null-folder](https://user-images.githubusercontent.com/41313813/148516784-65ead4f7-cd23-40f2-825f-264871a7c87e.png)

**Comment by anvithks** [comment]
Thanks @PravinRanjan10. Seems like this issue is in the folder creation. The object upload was fixed.
