### ISSUE TITLE
Add support for custom tiers in SODA Multicloud.

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/dashboard#523]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
On-premise means the on-premise object storage or other too?

**Comment by anvithks** [comment]
> On-premise means the on-premise object storage or other too?

The name of the task was created when the details were not clear. It is now updated.
