### ISSUE TITLE
Support Hetrogenous Object storage 

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#524]
**Issue/Feature Description:**
Umbrella task for all the Heterogeneous Object Storage
Note: Link all the issues here

- [x] related issue #522
- [ ] #523 
- [x] #527 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
Custom bucket tier feature is being tracked in #523 .
