### ISSUE TITLE
[Delfin UI] Support Host Mapping management for Heterogeneous framework from Dashboard

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/dashboard#593]
**Issue/Feature Description:**
Display the Host mapping alongwith the relationship between resources and host.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Delfin project will be adding support for Host mapping and provide APIs for host mapping management for the Heterogeneous Storage Framework.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Sample UI wireframe is prepared, needs discussion with Delfin team. 
     - Host Mapping Masking View : Finalize Dashboard View.
