### ISSUE TITLE
Dashboard displays SSP even though installer has SSP as false

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/dashboard#615]
**Issue/Feature Description:**
Installed SODA with latest installer release. Installer flag for enable_storage_service_plan is false but dashboard shows Enable SSP

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Feature issue

**How to reproduce, in case of a bug:**
Install SODA with installer v1.3.2 and Dashboard v1.3.3. make storage_service_plan as false (by default). Open Dashboard, it shows only Service plan

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
![image](https://user-images.githubusercontent.com/48085413/123636410-77877180-d83a-11eb-929d-019bf2cb77b6.png)
![image](https://user-images.githubusercontent.com/48085413/123636472-8a01ab00-d83a-11eb-9ff9-c2417cefa268.png)
![image](https://user-images.githubusercontent.com/48085413/123636536-9d147b00-d83a-11eb-9890-bba9b9b8ef73.png)

**Comment by anvithks** [comment]
After inspecting the environment and discussing this the issue was located in the `entrypoint.sh` file.
The environment variable was being written to the runtime.json file as a string instead of a boolean.
