### ISSUE TITLE
Update the version of SODA Dashboard version from `1.0.0` to the latest version `1.4.0`

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/dashboard#627]
**Issue/Feature Description:**
The version of the SODA Dashboard in the `package.json` file is still shown as `1.0.0`. The latest release version of the SODA Dashboard is `1.4.0`. 

https://github.com/sodafoundation/dashboard/blob/69d4fa01afd5e37dc1ffbb4c62506e7032525160/package.json#L3

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
This needs to be fixed to ensure that the correct version number is displayed and for consistency/

**How to reproduce, in case of a bug:**
1. Clone the repository.
2. Edit the `package.json` file.
3. The `version` value is `1.0.0`

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### Developers Guide to setup Development environment
The developer guide to setup a development environment can be found [here](https://docs.sodafoundation.io/guides/developer-guides/dashboard/)

**Comment by ikabir21** [comment]
i want to fix it

**Comment by anvithks** [comment]
@ikabir21 go ahead and raise the PR. Let me know if you need any help. You can also join the Slack channel `#soda-osi-2021` at [SODA Slack](https://sodafoundation.io/slack/)

**Comment by anvithks** [comment]
Thank you for your contribution @ikabir21
