### ISSUE TITLE
Responsiveness of nav-bar

### ISSUE THREAD

**Issue by vermastra** [sodafoundation/dashboard#636]
### Issue Discription:
The nav-bar is not fully responsive.
For the screen of **size 1024** the texts of nav-bar are over-flowing.

This gives bad UI to the users having screen size 1024 (range 1000-1300).

![Screenshot (39)](https://user-images.githubusercontent.com/78556885/135640467-e2122d56-205a-4302-b72d-fd13a1c2ca99.png)
![Screenshot (41)](https://user-images.githubusercontent.com/78556885/135640494-34329b38-5c9f-41ae-bae7-b6e8c29632df.png)

**Comment by anvithks** [comment]
The screenshots shared above are from the SODA Foundation [website](https://sodafoundation.io).
This repository is for the SODA Dashboard.
You can raise issues for the SODA website at this [repository](https://github.com/sodafoundation/website)
