### ISSUE TITLE
UI breaking because backend value not present

### ISSUE THREAD

**Issue by ravisaxena23** [sodafoundation/dashboard#648]
**Issue Description:**
we get a console error because the backend is not present we should add a proper check for backend values. if it is not present loop should not run.
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
UI might break in future
**How to reproduce, in case of a bug:**
go to the service page
![Screenshot (5)](https://user-images.githubusercontent.com/44205807/165085677-8d36e49c-369c-4d66-b88b-355780ff1957.png)

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

SodaCode2022

**Comment by anvithks** [comment]
#SODA-ISSUE-ACCEPTED
