### ISSUE TITLE
Invalid URL changes should redirect to home component

### ISSUE THREAD

**Issue by ravisaxena23** [sodafoundation/dashboard#653]
**Issue/Feature Description:**
Invalid URL changes should redirect to the home component.
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
suppose that you directly changed the URL in the search box. In case it is a wrong URL we get a console error. 
**How to reproduce, in case of a bug:**
search any URL in the search box.
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
![Screenshot (13)](https://user-images.githubusercontent.com/44205807/165213942-a7eb039f-1360-4c1c-a27d-6ff64b0023d1.png)

SODACODE2022

**Comment by anvithks** [comment]
#SODACODE-ISSUE-ACCEPTED
