### ISSUE TITLE
clicking on soda logo at home page redirect to home with white background

### ISSUE THREAD

**Issue by ravisaxena23** [sodafoundation/dashboard#656]
**Issue/Feature Description:**
log in and go to a profile page. then click on the soda logo. you will be redirected to the home page. but it will come in white background. which ideally should be black.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
this issue causes discrepancy for the user. also, it distorts the symmetry of the soda dashboard.

**How to reproduce, in case of a bug:**
login -> profile -> click on soda logo
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
#SODACODE2022 label

**Comment by skdwriting** [comment]
Accepted

**Comment by anvithks** [comment]
#SODACODE-ISSUE-ACCEPTED
