### ISSUE TITLE
Search from address bar does not change the active item in sidebar menu

### ISSUE THREAD

**Issue by ravisaxena23** [sodafoundation/dashboard#658]
**Issue/Feature Description:**
Search from the address bar does not change the active item in the sidebar menu.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
when the user changes the URL in the address bar soda dashboard takes the user to the desired location. but the active menu in the sidebar is not changed. this causes confusion for the user and decreases the UX.

**How to reproduce, in case of a bug:**
login -> go to buckets -> type /profile in address bar.
![Screenshot (28)](https://user-images.githubusercontent.com/44205807/166090643-b149e29a-d529-41f2-a713-e652421d34d8.png)
![Screenshot (29)](https://user-images.githubusercontent.com/44205807/166090644-8827d6de-113e-4989-b159-4726cda8a0e5.png)
![SODA Dashboard](https://user-images.githubusercontent.com/44205807/166090736-0473bd32-5dce-4064-be37-07fba9fb3ffb.png)

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by anvithks** [comment]
#SODA-ISSUE-ACCEPTED

**Comment by ravisaxena23** [comment]
#659
